describe('proxima', () => {
  it('loads the homepage', () => {
    cy.visit('https://admin.proxima.ng/')
    cy.url().should('include', 'proxima.ng')
    cy.title().should('not.be.empty')
    cy.get('#email').should('be.visible').type('ayanloyesegun+9@gmail.com')
    cy.get('#password').should('be.visible').type('Password@@1')
    cy.get('.ant-checkbox-label').click()
    cy.get('.ant-form > .justify-center').should('be.visible').click()
    cy.url().should('include', 'dashboard')
    cy.get(':nth-child(2) > .w-full > .font-medium').should('be.visible').click()
     cy.get('.font-sora').should('be.visible').click()
    cy.get('.buttondiv > .w-fit').should('be.visible').click()
    cy.get('.gap-4 > :nth-child(1) > .text-sm').should('be.visible')
    cy.get('#firstName').should('be.visible').type('Oluwaseun')
    cy.get('#lastName').should('be.visible').type('faile')
    cy.get('#email').should('be.visible').type('faileoluwaseun2017@gmail.com')
    cy.get(':nth-child(3) > .font-medium').should('be.visible').click()
    cy.get('.ant-select-selection-item').should('be.visible').click()
    cy.get('#phone').should('be.visible').type('08123456789')
    cy.get(':nth-child(3) > .font-medium').should('be.visible').click()
  })
})
